/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2025-06-19 00:12:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/KARIM/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1733348684292L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" - Admin Panel</title>\n");
      out.write("\n");
      out.write("    <!-- Dépendances CSS communes -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Icônes utilisées par la sidebar (Boxicons) -->\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("\n");
      out.write("    <!-- CSS pour la Sidebar et la mise en page principale -->\n");
      out.write("    <style>\n");
      out.write("        @import url(\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\");\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; font-family: \"Poppins\", sans-serif; }\n");
      out.write("\n");
      out.write("        /* Styles de la Sidebar */\n");
      out.write("        .sidebar { position: fixed; top: 0; left: 0; height: 100%; width: 260px; background: #11101d; z-index: 100; transition: all 0.5s ease; }\n");
      out.write("        .sidebar.close { width: 78px; }\n");
      out.write("        .sidebar .logo-details { height: 60px; width: 100%; display: flex; align-items: center; }\n");
      out.write("        .sidebar .logo-details i { font-size: 30px; color: #fff; height: 50px; min-width: 78px; text-align: center; line-height: 50px; }\n");
      out.write("        .sidebar .logo-details .logo_name { font-size: 22px; color: #fff; font-weight: 600; transition: 0.3s ease; transition-delay: 0.1s; }\n");
      out.write("        .sidebar.close .logo-details .logo_name { transition-delay: 0s; opacity: 0; pointer-events: none; }\n");
      out.write("        .sidebar .nav-links { height: 100%; padding: 30px 0 150px 0; overflow: auto; }\n");
      out.write("        .sidebar.close .nav-links { overflow: visible; }\n");
      out.write("        .sidebar .nav-links::-webkit-scrollbar { display: none; }\n");
      out.write("        .sidebar .nav-links li { position: relative; list-style: none; transition: all 0.4s ease; }\n");
      out.write("        .sidebar .nav-links li:hover { background: #1d1b31; }\n");
      out.write("        .sidebar .nav-links li .iocn-link { display: flex; align-items: center; justify-content: space-between; }\n");
      out.write("        .sidebar.close .nav-links li .iocn-link { display: block }\n");
      out.write("        .sidebar .nav-links li i { height: 50px; min-width: 78px; text-align: center; line-height: 50px; color: #fff; font-size: 20px; cursor: pointer; transition: all 0.3s ease; }\n");
      out.write("        .sidebar .nav-links li.showMenu i.arrow { transform: rotate(-180deg); }\n");
      out.write("        .sidebar.close .nav-links i.arrow { display: none; }\n");
      out.write("        .sidebar .nav-links li a { display: flex; align-items: center; text-decoration: none; }\n");
      out.write("        .sidebar .nav-links li a .link_name { font-size: 18px; font-weight: 400; color: #fff; transition: all 0.4s ease; }\n");
      out.write("        .sidebar.close .nav-links li a .link_name { opacity: 0; pointer-events: none; }\n");
      out.write("        .sidebar .nav-links li .sub-menu { padding: 6px 6px 14px 80px; margin-top: -10px; background: #1d1b31; display: none; }\n");
      out.write("        .sidebar .nav-links li.showMenu .sub-menu { display: block; }\n");
      out.write("        .sidebar .nav-links li .sub-menu a { color: #fff; font-size: 15px; padding: 5px 0; white-space: nowrap; opacity: 0.6; transition: all 0.3s ease; }\n");
      out.write("        .sidebar .nav-links li .sub-menu a:hover { opacity: 1; }\n");
      out.write("        .sidebar.close .nav-links li .sub-menu { position: absolute; left: 100%; top: -10px; margin-top: 0; padding: 10px 20px; border-radius: 0 6px 6px 0; opacity: 0; display: block; pointer-events: none; transition: 0s; }\n");
      out.write("        .sidebar.close .nav-links li:hover .sub-menu { top: 0; opacity: 1; pointer-events: auto; transition: all 0.4s ease; }\n");
      out.write("        .sidebar .nav-links li .sub-menu .link_name { display: none; }\n");
      out.write("        .sidebar.close .nav-links li .sub-menu .link_name { font-size: 18px; opacity: 1; display: block; }\n");
      out.write("        .sidebar .profile-details{ position: fixed; bottom: 0; width: 260px; display: flex; align-items: center; justify-content: space-between; background: #1d1b31; padding: 12px 0; transition: all 0.5s ease; }\n");
      out.write("        .sidebar.close .profile-details{ background: none; width: 78px; }\n");
      out.write("        .sidebar .profile-details .profile-content{ display: flex; align-items: center; }\n");
      out.write("        .sidebar .profile-details .name-job{ margin-left: -5px; color: #fff; }\n");
      out.write("\n");
      out.write("        /* Styles de la Section Principale */\n");
      out.write("        .home-section { position: relative; background: #f8f9fa; min-height: 100vh; left: 260px; width: calc(100% - 260px); transition: all 0.5s ease; }\n");
      out.write("        .sidebar.close ~ .home-section { left: 78px; width: calc(100% - 78px); }\n");
      out.write("        .home-section .home-content { padding: 0 20px; height: 60px; display: flex; align-items: center; }\n");
      out.write("        .home-section .home-content .bx-menu { color: #11101d; font-size: 35px; cursor: pointer; }\n");
      out.write("        .home-section .home-content .text { color: #11101d; font-size: 26px; font-weight: 600; margin-left: 15px; }\n");
      out.write("        .home-section .main-page-content { padding: 1rem 2rem; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragments/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"home-section\">\n");
      out.write("        <div class=\"home-content\">\n");
      out.write("            <i class='bx bx-menu'></i>\n");
      out.write("            <span class=\"text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"main-page-content\">\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Scripts JavaScript -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Script pour l'interactivité de la Sidebar -->\n");
      out.write("    <script>\n");
      out.write("        let arrow = document.querySelectorAll(\".arrow\");\n");
      out.write("        for (var i = 0; i < arrow.length; i++) {\n");
      out.write("            arrow[i].addEventListener(\"click\", (e) => {\n");
      out.write("                let arrowParent = e.target.parentElement.parentElement;\n");
      out.write("                arrowParent.classList.toggle(\"showMenu\");\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        let sidebar = document.querySelector(\".sidebar\");\n");
      out.write("        let sidebarBtn = document.querySelector(\".bx-menu\");\n");
      out.write("        sidebarBtn.addEventListener(\"click\", () => {\n");
      out.write("            sidebar.classList.toggle(\"close\");\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/pages/layout.jsp(80,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty contentPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
          out.write("\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
